[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stackodoro-cli"
version = "0.1.0"
description = "Simple pomodoro cli app that fill as bookshelf with a random book every session"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "urwid",
    "sounddevice>=0.4.6",
    "soundfile>=0.12.1",
    "numpy>=1.24.0",
    "soxr"
]

[project.scripts]
stackodoro = "stackodoro_cli.main:run"